### ISSUE TITLE
[Q&A] How to add custom headers before handshake?

### ISSUE THREAD

**Issue by duongxinh2003** [Scrawach/gdstomp#1]
When upgrading the HTTP request to 101, no way to set headers (for example origin, sesson_id,..) before handshake. I think we need to add param from .connect_to_host(url, headers) method

**Comment by Scrawach** [comment]
Hi! Is this a question about working through websockets? [WebSocketPeer ](https://docs.godotengine.org/en/stable/classes/class_websocketpeer.html#class-websocketpeer-property-handshake-headers) allows you to specify [handshake headers](https://docs.godotengine.org/en/stable/classes/class_websocketpeer.html#class-websocketpeer-property-handshake-headers) to be sent at the time of WebSocket handshake. Using `gdstomp` this could be expressed something like this: 

```gdscript
stomp_client.connection.peer.handshake_headers = ...
```

But it's long. I think your suggestion would work fine. The problem here is that `gdstomp` can work over both TCP and WebSocket. And I would like to keep this possibility and ease of switching between them. We should think about this point.

In any case, it doesn't work for Web exports. [Documentation](https://docs.godotengine.org/en/stable/classes/class_websocketpeer.html#class-websocketpeer-property-handshake-headers):

```
Note: Not supported in Web exports due to browsers' restrictions.
```

In my opinion, if it's not Web export, it's better to use TCP. 

Or did I misunderstand the question? Can you please clarify it?

**Comment by Scrawach** [comment]
After all, I think a good point for passing headers would be the constructor.

```gdscript
WebSTOMPConnection.new(handshake_headers)
```

Then create client:

```gdscript
var stomp_client: STOMPClient = STOMP.over_websockets(handshake_headers)
```

**Comment by duongxinh2003** [comment]
> After all, I think a good point for passing headers would be the constructor.
> 
> ```gdscript
> WebSTOMPConnection.new(handshake_headers)
> ```
> 
> Then create client:
> 
> ```gdscript
> var stomp_client: STOMPClient = STOMP.over_websockets(handshake_headers)
> ```

That's what I mean. In Godot's document, if you want to set headers before handshake using stomp over WebSocket, you can use `WebSocketPeer` like:
```
var peer: WebSocketPeer = WebSocketPeer.new()
peer.handshake_headers = PackedStringArray(["Origin: http://localhost:6789"])
```
As you say, passing some headers through the constructor looks good

**Comment by Scrawach** [comment]
The problem is solved by passing optional parameters through the factory method. Thank you for feedback :)
